apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: boardgame
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30090
